DRECK_TEXTURE_ATLAS_OUTPUT_TYPE_SCRIPT_PATHS += ./plugins/texture-atlas/generated/index.ts
DRECK_TEXTURE_ATLAS_OUTPUT_PNG_PATHS += ./plugins/texture-atlas/generated/index.png

DRECK_GENERATED_PATHS += $(DRECK_TEXTURE_ATLAS_OUTPUT_TYPE_SCRIPT_PATHS) $(DRECK_TEXTURE_ATLAS_OUTPUT_PNG_PATHS)
